org.gradle.jvmargs=-Xmx6G -Dfile.encoding=UTF-8
org.gradle.daemon=false

mod_version=1.12.0-port
minecraft_version=1.21.1
minecraft_range=[1.21.1,1.21.2)
neo_version=21.1.241
neo_range=[21.1.0,21.2.0)
loader_range=[4,)
parchment_minecraft_version=1.21.1
parchment_version=2024.11.17
jei_version=19.39.0.368
